### ISSUE TITLE
Chatting server SQS 연결시 발생한 에러

### ISSUE THREAD

**Issue by JunHyeongAn** [AKYC-chat/akyc-chatting#1]
**버그관련 내용**
SQS FIFO에 메시지를 넣으려고 할때 에러가 발생합니다.

**상황 재현**
1. 웹소켓에서 메시지 받아옴
2. 받아온 메시지를 Message Handler Send 메서드를 사용해 전송 시도
3. 에러발생

**원하는 결과 값**
SQS에 메시지가 들어가고 해당 메시지 아이디가 반환

**스크린샷**
<img width="765" alt="image" src="https://github.com/AKYC-chat/akyc-chatting/assets/99971427/85e0494c-7063-44aa-b6d1-c92fd8885abd">

**컴퓨터 정보**
 - OS: [macOS]
 - Browser [postman]

**추가 전달 사항**

**Comment by yjkim-9412** [comment]
standard queue 에 dulicationId 를 넣어 발생한 문제입니다. fifo  queue 를 가져오게 수정하였습니다.
