### ISSUE TITLE
메세지큐에서 메세지를 받아올 때 에러 발생

### ISSUE THREAD

**Issue by JunHyeongAn** [AKYC-chat/akyc-chatting#4]
**버그관련 내용**
MessageHandler ReceiveMessage()를 실행했을때 에러가 발생합니다.

**상황 재현**
-

**원하는 결과 값**
큐에 담긴 메세지 수신

**스크린샷**
![image](https://github.com/AKYC-chat/akyc-chatting/assets/99971427/97804127-066a-4371-9b7f-d97cdcbf2bc4)
![image](https://github.com/AKYC-chat/akyc-chatting/assets/99971427/4f69b69c-69ea-4f64-92f0-f74548553fd1)
![image](https://github.com/AKYC-chat/akyc-chatting/assets/99971427/8e69368c-c624-470c-bb24-be6dbfb867bc)

**컴퓨터 정보**
 - OS: [macOS]
 - Browser [vscode]
 - Version -

**스마트폰 정보**

**추가 전달 사항**
-

**Comment by yjkim-9412** [comment]
현재 Queue에서 받아온 메세지내의 전송, 수신 날짜에 포함 되어있는 nanosecond 문자열을 변환 과정에서 문제가 발생 했습니다. 
이는 현재 해결 되었으며 추후 commit에 반영됩니다.

**Comment by yjkim-9412** [comment]
문제가 해결되었습니다. 자세한 commit history: https://github.com/AKYC-chat/akyc-chatting/commit/f1e40c05ff5a3386ffbedb5c4a26c911b3ecc1cc

**Comment by JunHyeongAn** [comment]
수정된거 확인 했습니다!
